### PR TITLE
Centos7, backup

### PR DESCRIPTION
**Pull request by martbhell**
Thanks for a good role! I've used a fork for 3-4 months with the following changes on CentOS7:

 - backup chrony.conf when templating it in
 - update vars to make the template on centos7 have the same settings as the default one on centos7
 - add option to remove the ntp package
 - ansible2 updates
 - use the package module

### CODE REVIEW

**Comment by marklee77** [comment]
I think you need to also update the .travis.yml file to install ansible 2.

**Comment by martbhell** [comment]
The test installs ansible all 1.4.4+dfsg-1~ubuntu12.04.1 
Checking if it works better in trusty.

**Comment by martbhell** [comment]
No, trusty still has ansible 1.5. Trying to install ansible with pip

**Comment by martbhell** [comment]
OK it's green.

**Pull request merged**
