### PR TITLE
Removing chrony role symlink

### PR DESCRIPTION
**Pull request by nextrevision**
This removes the situation of a recursive symlink loop when added as a submodule.

### CODE REVIEW

**Comment by marklee77** [comment]
could you give an example of when having the static symlink causes a problem?

**Comment by nextrevision** [comment]
I'll try and reproduce the issue and paste the log output tomorrow. I was running into an issue with vagrant when starting a machine, during it's rsync process, it encountered the infinite loop when the role was installed as a git submodule.

**Comment by nextrevision** [comment]
Here is the detailed log output from vagrant:
```
==> control01: Rsyncing folder: /Users/demo/myansibleproject/ => /home/vagrant/sync
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/demo/myansibleproject/
Guest path: /home/vagrant/sync
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/Users/demo/myansibleproject/.vagrant/machines/control01/virtualbox/private_key' --exclude .vagrant/ /Users/demo/myansibleproject/ vagrant@127.0.0.1:/home/vagrant/sync
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
rsync: readlink "/Users/demo/myansibleproject/playbooks/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony/roles/chrony" failed: Too many levels of symbolic links (62)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(992) [sender=2.6.9]
```

It is using the ansible provisioner, pretty basic configuration. The problem lies with rsync, however.

If the role symlink is only used in development/testing of the role, then I think there is no need to have it exist in the repo and this PR should satisfy the testing requirements. But I'm not sure of all the different scenarios.

**Comment by marklee77** [comment]
Okay, interesting. What's your host operating system? OS X? I don't think vagrant is using rsync to provide the host->guest filesystem mapping for me, so I hadn't encountered this problem.

Yes, the point of the symlink is just to make the role work in the vagrant vm for testing.

**Pull request merged**
